app:
  csv:
    has-header: false
    delimiter: ","
    max-size-mb: 50
  date-cache:
    max-size: 100000
  calculation:
    inclusive-end-date: true
    parallelism: -1
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
server:
  port: 8080
logging:
  level:
    com.sirma.backend: INFO